project:
  type: website

website:
  title: "Slakkenverhalen uit België"
  description: "Excursies, projecten en verhalen over land- en zoetwaterslakken."
  back-to-top-navigation: true
  page-footer: 
    left: "Copyright 2026, Ward Langeraert"
    right:
      - icon: facebook
        href: https://www.facebook.com/groups/276789952465531
      - icon: github
        href:  https://github.com/wlangera/slakkenverhalen-belgie 

  navbar:
    left:
      - href: index.qmd
        text: Home

      - text: Projecten
        menu:
          - href: projecten/slak-in-du/index.qmd
            text: Slak-in-Du
          - href: projecten/platte-schijfhoren/index.qmd
            text: Platte schijfhoren

      - text: Excursies
        menu:
          - href: excursies/succinea-werkgroep/index.qmd
            text: Succinea werkgroep

      - href: blog/index.qmd
        text: Blog

      - href: soorten/index.qmd
        text: Soorten

      - href: about.qmd
        text: Over

    tools:
      - icon: facebook
        href: https://www.facebook.com/groups/276789952465531
      - icon: github
        href:  https://github.com/wlangera/slakkenverhalen-belgie

format:
  html:
    theme: cosmo
    toc: true
    lang: nl-BE
    css: styles/custom.css
