---
title: "Welkom"
listing:
  contents: blog
  type: table
  sort: "date desc"
  table-striped: true
  date-format: "D MMMM YYYY"
  fields: [title, date, author, description]
  exclude:
    title: "Blog"
---

## Welkom op Slakkenverhalen uit België 🐌

Welkom op deze website over **land- en zoetwaterslakken in België**. Op deze site wil ik veldobservaties, excursies en onderzoeksprojecten delen, en mensen enthousiast maken voor deze vaak over het hoofd geziene dieren. Of je nu een natuurliefhebber bent, een student, of gewoon nieuwsgierig, hier vind je informatie, verhalen en praktische tips over het vinden en herkennen van slakken.

Op zoek naar **nuttige boeken, artikels, presentaties ...** over de land- en zoetwaterslakken in België? Je vindt het [hier](https://onedrive.live.com/?id=AFB71FDA01EA9B3D%21118&cid=AFB71FDA01EA9B3D&redeem=aHR0cHM6Ly8xZHJ2Lm1zL2YvYy9hZmI3MWZkYTAxZWE5YjNkL0VqMmI2Z0hhSDdjZ2dLOTJBQUFBQUFBQl9feG5Id3BFdEZPTjJ1NFYzcFM1VWc%5FZmJjbGlkPUl3WTJ4amF3UWF0ZUJsZUhSdUEyRmxiUUl4TUFCaWNtbGtFVEJrTm5kM1ZEQkROVEUyTkZoNVpHRlljM0owWXdaaGNIQmZhV1FRTWpJeU1ETTVNVGM0T0RJd01EZzVNZ0FCSGtFMlc0M0Z4MVZtQ252UHBoTnJJZ1RvazdVbFV2bDBCVnhWbms3YjJkQVBXZ2ViR2FmMXRQSE1qZVpyX2FlbV93NkN6d0xYMzVrZFQ4OXlPOFZEcjhR).

## Wat vind je op deze site?

-   **Projecten**: uitgebreide onderzoeksprojecten
-   **Excursies**: verslagen van veldbezoeken
-   **Blog**: korte verhalen over bijzondere ontdekkingen, ervaringen in het veld en tips voor slakkenonderzoek
-   **Soorten**: informatie over specifieke land- en waterslakken in België

## Laatste nieuws

Hier vind je de meest recente blogposts met updates, ontdekkingen en interessante observaties.

::: {#sample-listings}
:::
