---
title: "Succinea werkgroep"
---

## De Succinea werkgroep

De **Succinea werkgroep** is een werkgroep rond land- en zoetwatermollusken binnen de Koninklijke Belgische Vereniging voor Conchyliologie. De groep brengt onderzoekers, natuurliefhebbers en vrijwilligers samen die geïnteresseerd zijn in de studie van slakken en andere weekdieren in België.

Binnen de werkgroep lopen verschillende projecten, waaronder het **Slak-in-Du project**, dat de molluskenfauna van de Belgische kustduinen opnieuw in kaart brengt, en het **Najadenproject**, een langlopend onderzoek naar de verspreiding van grote zoetwatermosselen in Vlaanderen en België.

Een belangrijk onderdeel van de activiteiten van de werkgroep zijn **veldexcursies**. Tijdens deze excursies wordt de molluskenfauna van specifieke gebieden onderzocht en geïnventariseerd. Naast excursies organiseert de werkgroep ook **determinatievergaderingen**, waar recent verzameld materiaal wordt bestudeerd en besproken, of waar een bepaalde soort of groep van land- of zoetwatermollusken centraal staat.

Meer informatie over de werkgroep en haar activiteiten vind je op de website van de  
[Koninklijke Belgische Vereniging voor Conchyliologie](https://www.konbvc.be/varia/werkgroepen/land-en-zoetwatermollusken/).

## Excursies

Op deze pagina worden excursies verzameld die georganiseerd werden in het kader van de Succinea werkgroep.

> Verslagen volgen binnenkort
