---
title: "Eindelijk een naam voor het mysterieuze brakwaterslakje"
date: 2026-06-12
author: "Ward Langeraert"
description: "De mysterieuze 'vreemde speldhoren' is beschreven als een nieuwe soort *Koloonella peregrina*."
categories: [nieuwe soort, artikel, brak water]
---

# Eindelijk een naam voor het mysterieuze brakwaterslakje

Tien jaar geleden dook in Nederland in licht brakwater een piepklein slakje op dat niemand kon thuisbrengen. Het slechts twee millimeter grote diertje behoorde tot de familie van de Murchisonellidae, maar bleek niet overeen te komen met een bekende soort. Omdat het vermoedelijk om een exotische nieuwkomer ging, kreeg het voorlopig de toepasselijke Nederlandse naam ‘vreemde speldhoren’ ([www.naturetoday.com](https://www.naturetoday.com/intl/nl/nature-reports/message/?msg=23072)).

In een [recent verschenen artikel in Basteria](https://basteria.nl/?fbclid=IwY2xjawSZACZleHRuA2FlbQIxMQBzcnRjBmFwcF9pZBAyMjIwMzkxNzg4MjAwODkyAAEeXdtMShTlXf5jLxQIkULDfJmnYPgESOAOlOhi0H3ln8FdnWP2d16H2q3CU0Y_aem_DVHRQ6s3Ld6fZnLd7aQJPQ) is de soort officieel beschreven als *Koloonella peregrina* Bakker et al., 2026. De soortnaam 'peregrina' betekent ‘vreemdeling’ of ‘reiziger’ en verwijst naar haar niet-inheemse karakter en mysterieuze herkomst.

De eerste Europese populatie werd in 2014 ontdekt in de Finse Golf. Kort daarna werd de soort ook op meerdere locaties in Nederland aangetroffen, waar ze inmiddels gevestigd lijkt te zijn. Ondanks uitgebreid onderzoek blijft onbekend waar de soort oorspronkelijk vandaan komt. Op basis van schelpkenmerken en de aanwezigheid van een karakteristiek kaakapparaat konden onderzoekers de soort onderbrengen in het geslacht 'Koloonella' en aantonen dat het inderdaad om een voor de wetenschap nieuwe soort gaat.

In Belgïe zou de soort ook al op 1 locatie zijn aangetroffen.
